title: Mayank Nagar
logo: /assets/img/profile-pic (5).png
description: Data Science Enthusiast
E-mail: nmayank.790@gmail.com
Mobile: +91-9302743973
Location: Pune, Maharashtra, India
#show_downloads: true
theme: jekyll-theme-minimal
